// Mocks generated by Mockito 5.4.0 from annotations
// in chat_astro/test/user_creation_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:chat_astro/core/utils/context_wrapper.dart' as _i4;
import 'package:chat_astro/core/utils/dialog_utils.dart' as _i8;
import 'package:chat_astro/core/utils/open_ai_utils.dart' as _i2;
import 'package:chat_astro/feature/user_creation/data/data_source/user_creation_remote_data_source_impl.dart'
    as _i5;
import 'package:chat_astro/feature/user_creation/domain/entities/user_profile_entity.dart'
    as _i7;
import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOpenAiUtils_0 extends _i1.SmartFake implements _i2.OpenAiUtils {
  _FakeOpenAiUtils_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBuildContext_1 extends _i1.SmartFake implements _i3.BuildContext {
  _FakeBuildContext_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContextWrapper_2 extends _i1.SmartFake
    implements _i4.ContextWrapper {
  _FakeContextWrapper_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThemeData_3 extends _i1.SmartFake implements _i3.ThemeData {
  _FakeThemeData_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [UserCreationRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCreationRemoteDataSourceImpl extends _i1.Mock
    implements _i5.UserCreationRemoteDataSourceImpl {
  MockUserCreationRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OpenAiUtils get openAiUtils => (super.noSuchMethod(
        Invocation.getter(#openAiUtils),
        returnValue: _FakeOpenAiUtils_0(
          this,
          Invocation.getter(#openAiUtils),
        ),
      ) as _i2.OpenAiUtils);
  @override
  _i6.Future<String> getUserProfileResponse(
          {required _i7.UserProfileEntity? userProfileEntity}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfileResponse,
          [],
          {#userProfileEntity: userProfileEntity},
        ),
        returnValue: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);
}

/// A class which mocks [ContextWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockContextWrapper extends _i1.Mock implements _i4.ContextWrapper {
  MockContextWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.BuildContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeBuildContext_1(
          this,
          Invocation.getter(#context),
        ),
      ) as _i3.BuildContext);
}

/// A class which mocks [DialogUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogUtils extends _i1.Mock implements _i8.DialogUtils {
  MockDialogUtils() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ContextWrapper get contextWrapper => (super.noSuchMethod(
        Invocation.getter(#contextWrapper),
        returnValue: _FakeContextWrapper_2(
          this,
          Invocation.getter(#contextWrapper),
        ),
      ) as _i4.ContextWrapper);
  @override
  _i3.ThemeData get pickerTheme => (super.noSuchMethod(
        Invocation.getter(#pickerTheme),
        returnValue: _FakeThemeData_3(
          this,
          Invocation.getter(#pickerTheme),
        ),
      ) as _i3.ThemeData);
  @override
  _i6.Future<DateTime?> showCustomDatePicker() => (super.noSuchMethod(
        Invocation.method(
          #showCustomDatePicker,
          [],
        ),
        returnValue: _i6.Future<DateTime?>.value(),
      ) as _i6.Future<DateTime?>);
  @override
  _i6.Future<_i3.TimeOfDay?> showCustomTimePicker() => (super.noSuchMethod(
        Invocation.method(
          #showCustomTimePicker,
          [],
        ),
        returnValue: _i6.Future<_i3.TimeOfDay?>.value(),
      ) as _i6.Future<_i3.TimeOfDay?>);
}
