name: chat_astro
description: simple astrology application with open ai integration
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  mockito: ^5.4.0
  logger: ^1.3.0
  shared_preferences: ^2.1.1
  intl: ^0.18.1
  dart_openai: ^1.9.91

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/backgrounds/user_data_generation_background.png
    - assets/images/scoor_icon.png